source "https://rubygems.org"
ruby "3.2.3"

gem "bootsnap",   ">= 1.4.4", require: false
gem "httparty",   "~> 0.22"
gem "jwt",        "~> 2.9"
gem "pg",         "~> 1.5"
gem "puma",       "~> 6.4"
gem "rack-cors",  "~> 2.0"
gem "rails",      "~> 7.2"

group :development, :test do
  gem "factory_bot_rails", "~> 6.4"
  gem "faker",             "~> 3.3"
  gem "rspec-rails",       "~> 7.0"
  gem "rubocop",           "~> 1.65", require: false
  gem "rubocop-rails",     "~> 2.25", require: false
  gem "rubocop-rspec",     "~> 3.0",  require: false
end

group :test do
  gem "shoulda-matchers", "~> 6.2"
  gem "simplecov",        require: false
  gem "webmock",          "~> 3.23"
end
